### ISSUE TITLE
NodeExecutionError: Node 1b-FODEstimation.

### ISSUE THREAD

**Issue by jmmneuro** [aramis-lab/clinica#687] opened 2022-06-19 06:30 UTC
This issue happens when I ran the dwi_connectome pipeline (Fig. 1). After checking the recorded command of 1b-FODEstimation in work directory , rerunning it and getting an error message(Fig. 2), I thought I had solved this problem and then I cut off those wrong output files(gm.mif and csf.mif) in the clinicaEnv/lib/python3.8/site-packages/nipype/interfaces/mrtrix3/reconst.py (Fig 3). Then I  ran the dwi_connectome again and got another problem(Fig 4).

![ͼƬ1](https://user-images.githubusercontent.com/107784923/174468747-4292a2cd-722d-4862-8779-0dd1e7f83438.jpg)
![ͼƬ2](https://user-images.githubusercontent.com/107784923/174468790-a66481a9-c39c-4547-9938-dc802a489855.png)
Figure 1

![ͼƬ3](https://user-images.githubusercontent.com/107784923/174468805-6080a7e8-8b54-4f72-bcd6-4d31bfb93478.png)
Figure 2

![ͼƬ4](https://user-images.githubusercontent.com/107784923/174468809-3f6e29cf-d4e4-4da5-af5d-1cc6f967e3fb.png)
Figure 3

![ͼƬ5](https://user-images.githubusercontent.com/107784923/174468817-a1022d0b-f015-4e78-8134-9d9e169cbda1.png)
Figure 4

**Comment by jmmneuro** [comment] 2022-06-19 08:27
I change the status of the usedefault in gm_odf and csf_odf from Ture to False, and rerun the code. wow, it works.

**Comment by omar-rifai** [comment] 2022-07-01 12:08
Hello @jmmneuro, Thanks for bringing this up. I will have a look at this and get back to you soon.

**Comment by jmmneuro** [comment] 2022-07-09 16:36
Thank you for your reply! Nipype version in my miniconda3 directory is also 1.8.2.

**Comment by omar-rifai** [comment] 2022-07-20 13:38
My bad, we were actually using a vendored version of this interface which had these lines commented. The PR https://github.com/aramis-lab/clinica/pull/642 removed this without testing for this pipeline.

Your solution seems to be the right one. This will be fixed in the next release.

Thank you for the heads up.

**Comment by ghisvail** [comment] 2022-07-21 10:22
`[ERROR] CSD algorithm expects a single input response function and single output FOD image`

Then the issue is in the [nipype interface](https://github.com/nipy/nipype/blob/71c7a7d5315714bad8c423a587ba15760dc00b77/nipype/interfaces/mrtrix3/reconst.py#L204) which sets all three files regardless of the chosen algorithm.

The solution is *not* to vendor a version ourselves and comment stuff out, but submit an issue upstream to get it fixed for everyone. Probably this `_list_outputs` method will need some more logic to handle this use case cleanly.

@jmmneuro feel free to forward this issue upstream if you find time. Otherwise, I'll deal with it when I ma back from vacation.

**Comment by omar-rifai** [comment] 2022-07-21 12:00
> `[ERROR] CSD algorithm expects a single input response function and single output FOD image`
> 
> Then the issue is in the [nipype interface](https://github.com/nipy/nipype/blob/71c7a7d5315714bad8c423a587ba15760dc00b77/nipype/interfaces/mrtrix3/reconst.py#L204) which sets all three files regardless of the chosen algorithm.
> 
> The solution is _not_ to vendor a version ourselves and comment stuff out, but submit an issue upstream to get it fixed for everyone. Probably this `_list_outputs` method will need some more logic to handle this use case cleanly.
> 
> @jmmneuro feel free to forward this issue upstream if you find time. Otherwise, I'll deal with it when I ma back from vacation.

@ghisvail, good point. It is definitely better to have a correct version upstream. Nonetheless, until then, I feel that vendoring the fix ourselves was a better option than simple crashing. I'll try to look into it if I have the time.

**Comment by ghisvail** [comment] 2022-07-21 12:16
@jmmneuro don't bother with forwarding. The issue is known upstream for a while and has a [solution](https://github.com/nipy/nipype/issues/2822#issuecomment-590319901).

The appropriate fix is to use the `ConstrainedSphericalDeconvolution` interface instead of `EstimateFOD`.

**Comment by omar-rifai** [comment] 2022-07-26 12:11
Fixed in new release.

**Closed by omar-rifai** 2022-07-26 12:11 UTC
Labels: bug
