### ISSUE TITLE
t1-volume-parcellation about AAL3

### ISSUE THREAD

**Issue by IRIS00123** [aramis-lab/clinica#502] opened 2021-11-11 03:24 UTC
**Description**
I want to use the AAL3 template. when i add it by myself, I face the following problem.
211111-11:19:15,11 nipype.workflow ERROR:
	 could not run node: t1-volume-parcellation.atlas_stats_node
211111-11:19:15,11 nipype.workflow ERROR:
	 could not run node: t1-volume-parcellation.atlas_stats_node

**Pipeline**
Which Clinica's Pipeline is concerned?
- t1-volume
t1-volume-parcellation

**Comment by omar-rifai** [comment] 2021-11-16 15:59
Hello, thank you for your interest in Clinica.

Can you please provide the full error log (as an attachment) so that we can help you find the issue.

Regards

**Comment by IRIS00123** [comment] 2021-11-17 02:05
The full error log has been attached, please check it, thank you!

Have you considered adding AAL3 to the official code? AAL3 adds a number of brain areas not previously defined, but of interest in many neuroimaging investigations. 

[clinica.log](https://github.com/aramis-lab/clinica/files/7551110/clinica.log)

**Comment by omar-rifai** [comment] 2021-11-18 09:54
Thank you ! it looks like the mask provided is of the wrong dimension:

`masked_data[np.invert(current_mask_label)] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 121 but corresponding boolean dimension is 181`

@MatthieuJoulot is trying to replicate

**Comment by MatthieuJoulot** [comment] 2021-11-22 13:41
Hi @IRIS00123, 

I've managed to reproduce the bug you have. The problem is with the dimension of the atlas you are giving t1-volume.

Our atlas are meant to be used with a pixel dimension of 1.5mm and a dimension of (121, 145, 121).
To solve this, I used FSLeyes and used the fonction resample. You just have to change the pixel dimension to 1.5. It doesn't matter that the values are not precisely 121 and 145, it's rounded during the saving.
Afterwards you can run the pipeline again, it should work.

Right now, it is not a priority for us, so we won't be adding AAL3 to our code.

If you have any other problems don't hesitate ! And if your problem is solved, please close the issue.

Have a good day

**Comment by IRIS00123** [comment] 2021-11-26 09:02
I think the error results in that I use the official AAL3 atlas, which is not a dimension of  (121, 145, 121).
The dimension of the official AAL2 and AAL3 atlases are not (121, 145, 121), but the official AAL2 atlas of Clinical is a dimension of  (121, 145, 121). Could you please explain how to convert it? Could you provide the AAL3 atlas with a dimension of  (121, 145, 121)? Thank you very much.

Have a good day.

**Comment by MatthieuJoulot** [comment] 2021-11-26 15:52
Yes, this is the problem.

To convert it, you have use **FSLeyes** (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes). Once you have it, load the atlas in FSLeyes. Then you can use the resample function, and get pixeldim to 1.5mm. The dimension of the atlas will be changed accordingly into (121, 145, 121) and a few decimals. The decimals do not matter, they will be cut out during the saving.
And after that you will be able to use the atlas ! I hope that I was clear, otherwise, do ask again !

And I cannot provide the AAL3 atlas for licensing reasons, sorry.

Have a good day.

**Comment by IRIS00123** [comment] 2021-11-28 11:14
Thank you very much for your patience. According to what you said, the dimension of the atlas is transformed successfully. However, the converted atlas has some noise, as shown in the attached file. Do you encounter this problem when resampling?

Can you please tell me the parameters of resampling in FSLeyes,  such as origin, interpolation, smoothing?
 
Thanks again.

Have a good day.

![noise](https://user-images.githubusercontent.com/34446461/143765424-d4cb368d-0e1b-41f1-b8fb-2f3af81ac4ef.png)

**Comment by MatthieuJoulot** [comment] 2021-11-29 15:31
Hi, I have not encountered  this problem.
The parameters I have used are as they are in the screen below.
<img width="374" alt="Screenshot 2021-11-29 at 16 16 44" src="https://user-images.githubusercontent.com/85217698/143895805-a10ee9ba-26ee-4373-b27f-dde5f70b8394.png">
And the result I have is the following:
<img width="1290" alt="Screenshot 2021-11-29 at 16 21 56" src="https://user-images.githubusercontent.com/85217698/143895987-6bcd801d-df81-4c69-9755-ff1be61466d4.png">
I hope this helps !

Have a good day

**Comment by alexandreroutier** [comment] 2021-11-29 16:39
Hi @MatthieuJoulot and @IRIS00123,

I believe you must use the "Nearest neighbour" interpolation, otherwise, you will face weird issues that would explain 3D Slicer's snapshot from IRIS00123.


Best,
Alexandre

**Comment by IRIS00123** [comment] 2021-11-30 01:54
Hi  @alexandreroutier,

Thank you for your reminder. It is exactly as you said.

Thanks.

**Closed** 2021-11-30 01:55 UTC
