### ISSUE TITLE
machine learning pipeline hangs forever with ThreadPool with python 3

### ISSUE THREAD

**Issue by anbai106** [aramis-lab/clinica#100] opened 2020-06-14 18:40 UTC
Hello,

My environment is:
Ubutun 18.04, python 3.6, sklearn verison: 0.22.1

I found a potential bug for python 3 with the machine learning pipeline. It comes from the module of 
`from multiprocessing.pool import ThreadPool` for **_DualSVMAlgorithm_**.

The multi-thread pool hangs forever at this line: line 105 in **_clinica/clinica/pipelines/machine_learning/algorithm.py_** . Digging inside the function **_pool.join()_**, it hangs up at this line: line 662: **_self._worker_handler.join()_** in **_pool.py_**.

This does not happen when I ran it with python 2. I tried to debug but not able to find a solution.

I do not know if anyone has run the machine learning pipeline with the new version of Clinica?

Thank you

**Comment by alexandreroutier** [comment] 2020-06-16 07:01
Hi Hao,

Thanks for the issue and investigation.

Currently, non regression tests are done for `VertexBasedRepHoldOutDualSVM ` and `VoxelBasedKFoldDualSVM`:
https://github.com/aramis-lab/clinica/blob/dce08e128818cc27912d937736a3e698433da3b5/test/nonregression/test_run_pipelines.py#L709

From what you told me, you used ROI Atlas with 45 features, we will look later this issue (new release priority) :).

Alex

**Comment by anbai106** [comment] 2020-06-18 03:47
Hola,

I think I found the problem.
The problem is from this function: _**apply_async()**_. For Python 3, the second argument args=tuple(), which should be an optional arguement. In the source code, or maybe in python 2, this is a mandatory argument. More important, the _**.get()**_ attribute of the instance of this function should be called before:

`       inner_pool.close()`
`       inner_pool.join()`

Which is not the case in the current code. That's why it will stuck at  _**inner_pool.join()**_.

All the code regarding this function should be re-adapted.

**Comment by anbai106** [comment] 2020-06-25 01:58
I give here more feedback, since I am repeating some experiments for the AD-ML-DTI paper in python 3.

I finally found out where the problem is from: The issue is the not python version, neither Sklearn version it self. It seems that the slowness of the ML pipeline is due to the combination of **multiprocessing** and **scikit-learn**.

To replicate the issue, here is my environment settings: Ubuntu 18.04, sklearn: 0.23.1 and 0.22.1, multiprocessing is a python built-in module. The **SVC** function together with **pool = ThreadPool(self._n_threads)** is far more slow than normal! Thought all 8 CPUs are fully occupied.

With degradation to old version when I ran for the paper, (scikit-learn verison: 0.21.3) with both python 2 and python 3, the speed goes back to normal, quite fast!

You may encounter this issue when someone in the lab is going to use the ML pipeline under python 3. Workaround, but not elegant, is just to degrade the sklearn version.

Best regards

**Comment by omar-rifai** [comment] 2021-06-06 16:55
Hi there @anbai106 , @alexandreroutier,

I'm resuscitating this thread to see if we can close this issue. I have tried to run VertexBasedRepHoldOutDualSVM and VoxelBasedKFoldDualSVM from the updated non-regression tests and they seem to to run without issues. 

Is this thread still relevant? If so can you give me a bit more context? How can I replicate this issue?

Thank you !

**Comment by omar-rifai** [comment] 2021-11-23 14:50
Closing this issue due to inactivity.

**Closed by omar-rifai** 2021-11-23 14:50 UTC
